### ISSUE TITLE
Extending events add the new event type to @taxonomy.type ?

### ISSUE THREAD

**Issue by nsteinmetz** [kalebheitzman/grav-plugin-events#33]
Hi,

I would like to customise the event on admin side to add a few fields. 

So I created a blueprint in my template named ``eventcvsq.yml`` containing:

``` yaml
title: Event CVSQ
'@extends':
    type: event
    context: blueprints://event

form:
  fields:
    tabs:
      fields:
    
        contact:
          type: tab
          title: Event
          fields:
            header.event.cvsq_type:
              type: select
              label: Event CVSQ
              options:
                'ml': 'Manches Libres Laser'
                'cf': 'Championnat de Flotte Laser'
                'fc': 'Fête du club'
                'al': 'Animation Libre Laser'
                'rc': 'Régate CVSQ'
                'ce': 'Coupe Entreprise'
                'au': 'Autre'
```
So on admin side, it works as expected.

My need would be at the end to filter on ``"@taxonomy.type": "eventcvsq"`` like this:

``` twig
<div class="row actualite" data-equalizer data-equalize-on="medium" id="cvsq-actualite">
    <div class="small-12 medium-4 large-4 columns">
        <div class="cvsq-block" data-equalizer-watch>
        <h4>Prochains &eacute;v&eacute;nements</h4>
        {% set events =
            page.collection({
                'items': {
                    '@taxonomy.type': 'eventcvsq',
            },
                'dateRange': {
                    'start': datetools.today,
                    'end': datetools.endOfYear
                },
                'order': {
                    'by': 'date',
                    'dir': 'asc'
                },
                'limit': 15
            })
        %}
        {% for child in events %}
            {% include 'partials/event_homepage.html.twig' with {'eventcvsq':page, 'page':child, 'truncate':true} %}        
        {% endfor %}
    </div>
    </div>
```

I also added in the plugin setup the ``eventcvsq`` for the "Event template types" 

But I have no output. When I use ``dump(child.taxonomy)``, I can see that my new events does not have the taxonomy.type added automatically, in opposite to defaults events.

How could I propagate the taxonomy.type to my custom events ? I don't strictly need that I have a ``type`` that match ``eventcvsq``, I at least need that it's attached to ``type`` is equal to ``event``.

And for the ``calendar`` and ``events`` page, it does not show up neither :(

Thanks,
Nicolas
